site_name: RaspAP Documentation
repo_url: https://github.com/RaspAP/raspap-webgui
repo_name: RaspAP/raspap-webgui
edit_uri: /RaspAP/raspap-docs/edit/master/docs
theme:
  name: material
  logo: images/favicon-32x32.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: UA-187566692-1
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rasp_ap
    - icon: fontawesome/brands/github
      link: https://github.com/RaspAP/raspap-webgui
copyright: Copyright &copy; 2013 - 2022 <a href="https://github.com/RaspAP">RaspAP</a>
